-- ============================================================
-- CONTRATO MARCO — migración
-- Ejecutar en Neon SQL Editor (noc-dashboard prod).
-- ============================================================

-- 1. Crear tabla ContratoMarco
CREATE TABLE IF NOT EXISTS "ContratoMarco" (
  "id"         TEXT NOT NULL PRIMARY KEY,
  "siglasIm"   TEXT NOT NULL DEFAULT '',
  "company"    TEXT NOT NULL,
  "serviceRef" TEXT NOT NULL DEFAULT '',
  "note"       TEXT,
  "createdBy"  TEXT NOT NULL DEFAULT '',
  "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "ContratoMarco_siglasIm_idx"   ON "ContratoMarco" ("siglasIm");
CREATE INDEX IF NOT EXISTS "ContratoMarco_company_idx"    ON "ContratoMarco" ("company");
CREATE INDEX IF NOT EXISTS "ContratoMarco_serviceRef_idx" ON "ContratoMarco" ("serviceRef");

-- 2. Crear tabla ContratoMarcoIncident
CREATE TABLE IF NOT EXISTS "ContratoMarcoIncident" (
  "incidentId"  TEXT NOT NULL PRIMARY KEY,
  "openTime"    TIMESTAMP(3) NOT NULL,
  "status"      TEXT NOT NULL DEFAULT '',
  "company"     TEXT NOT NULL DEFAULT '',
  "serviceId"   TEXT NOT NULL DEFAULT '',
  "state"       TEXT NOT NULL DEFAULT '',
  "district"    TEXT NOT NULL DEFAULT '',
  "assignee"    TEXT,
  "group"       TEXT NOT NULL DEFAULT '',
  "matchedBy"   TEXT NOT NULL DEFAULT '',
  "flagged"     BOOLEAN NOT NULL DEFAULT false,
  "note"        TEXT,
  "dismissed"   BOOLEAN NOT NULL DEFAULT false,
  "resolvedAt"  TIMESTAMP(3),
  "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSeenAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "ContratoMarcoIncident_company_idx"     ON "ContratoMarcoIncident" ("company");
CREATE INDEX IF NOT EXISTS "ContratoMarcoIncident_serviceId_idx"   ON "ContratoMarcoIncident" ("serviceId");
CREATE INDEX IF NOT EXISTS "ContratoMarcoIncident_firstSeenAt_idx" ON "ContratoMarcoIncident" ("firstSeenAt");
CREATE INDEX IF NOT EXISTS "ContratoMarcoIncident_resolvedAt_idx"  ON "ContratoMarcoIncident" ("resolvedAt");

-- 3. Mover clientes que ya existen en ClienteTop hacia ContratoMarco
--    (copia siglasIm/serviceRef/note que ya tenían; los borra de ClienteTop)
WITH to_move AS (
  SELECT ct.*
  FROM "ClienteTop" ct
  WHERE lower(trim(ct.company)) IN (
    'archivo general de la nacion',
    'asea hidrocarburos',
    'comision nacional de hidrocarburos',
    'comision nacional de seguros y fianzas (cnsf)',
    'comision nacional de usuarios de servicios financieros (condusef)',
    'conacyt_care',
    'conahcyt',
    'conaliteg',
    'conanp pexa',
    'exportadora de sal',
    'fideicomiso de fomento minero',
    'financiera nacional de desarrollo agropecuario rural forestal y pesquero',
    'fonacot_care',
    'fondo nacional de fomento al turismo fonatur',
    'fondo nacional para el fomento de las artesanias (fonart)',
    'grupo aeroportuario ferroviario y de servicios auxiliares olmeca maya mexica',
    'imcine',
    'instituto de investigaciones dr. jose ma. luis mora_care',
    'instituto mexicano de la propiedad industrial (impi)',
    'instituto nacional de ecologia y cambio climatico',
    'instituto nacional de neurologia y neurocirugia',
    'instituto nacional de salud publica',
    'instituto para la proteccion al ahorro bancario care',
    'procuraduria de la defensa del contribuyente (prodecon)',
    'profepa',
    'secretaria de economia',
    'secretaria de educacion publica sep',
    'secretaria de relaciones exteriores',
    'secretaria ejecutiva del sistema nacional anticorrupcion (sesna)',
    'semarnat',
    'senasica',
    'administracion portuaria integral de veracruz',
    'aefcm',
    'aeropuertos y servicios auxiliares',
    'agencia espacial mexicana',
    'agroasemex',
    'b drive - insabi',
    'b drive - profepa',
    'b drive - sfp',
    'b drive cimat',
    'b drive imer',
    'b drive inprf',
    'b drive it - impi',
    'b drive spr',
    'casa de moneda de mexico',
    'centro de ensenanza tecnica industrial',
    'centro de investigacion en matematicas',
    'centro de investigacion y asistencia en tecnologia y diseno del estado de jalisco',
    'centro de investigacion y docencia economicas',
    'centro federal de conciliacion y registro laboral',
    'centro geo',
    'ciateq',
    'cibnor',
    'cineteca nacional',
    'cinvestav',
    'cnsf oficina corporativa',
    'colegio nacional de educacion profesional tecnica',
    'comision nacional bancaria y de valores',
    'comision nacional de cultura fisica y deporte',
    'comision nacional de seguridad nuclear y salvaguardias',
    'comision nacional de vivienda',
    'conapesca',
    'condusef oficinas remotas',
    'consejo nacional de fomento educativo',
    'conuee',
    'fideicomiso de riesgo compartido',
    'fifonafe',
    'fonatur infraestructura',
    'fondo nacional para el fomento de las artesanias',
    'grupo aeroportuario de la ciudad de mexico',
    'hospital general de mexico',
    'hospital infantil de mexico federico gomez',
    'hospital regional de alta especialidad del bajio',
    'imp',
    'imss red de funcionarios',
    'indaabin',
    'ineel',
    'inifed',
    'instituto de ecologia (inecol)',
    'instituto mexicano de la radio',
    'instituto nacional de antropologia e historia',
    'instituto nacional de cardiologia ignacio chavez',
    'instituto nacional de geriatria',
    'instituto nacional de perinatologia',
    'instituto nacional de psiquiatria ramon de la fuente muniz',
    'instituto nacional de enfermedades respiratorias ismael cosio villegas',
    'instituto nacional para la educacion de los adultos',
    'instituto potosino de investigacion cientifica y tecnologica',
    'ipn canal once',
    'itson',
    'loteria nacional',
    'organismo promotor de medios audiovisuales',
    'presidencia de la republica',
    'procuraduria agraria',
    'procuraduria de la defensa del contribuyente',
    'procuraduria federal del consumidor',
    'pronabive',
    'registro agrario nacional',
    'sader',
    'secretaria de medio ambiente y recursos naturales',
    'sedatu',
    'sener',
    'sep',
    'sep oficinas corporativas',
    'servicio geologico mexicano',
    'siap',
    'sistema nacional para el desarrollo integral de la familia',
    'snics',
    'television metropolitana',
    'tribunal superior agrario',
    'universidad pedagogica nacional',
    'administradora de caja bienestar',
    'alto comisionado de las naciones unidas para los refugiados',
    'auditoria superior de la federacion',
    'centro de ingenieria y desarrollo industrial',
    'colegio de bachilleres',
    'comesa',
    'comision nacional de seguros y fianzas',
    'consejeria juridica del ejecutivo federal',
    'el colegio de la frontera sur',
    'fonhapo',
    'hospital juarez de mexico',
    'inai',
    'inapesca',
    'instituto mexicano de la juventud',
    'instituto mexicano de tecnologia del agua',
    'instituto mexicano del petroleo',
    'instituto nacional de ciencias penales',
    'itesi irapuato',
    'p.m.i. comercio internacional',
    'pmi comercio internacional express route',
    'radio sqcs',
    'scania comercial',
    'secretaria de economia data center',
    'secretaria de la funcion publica',
    'sectur',
    'sepomex',
    'sky',
    'unison',
    'sedatu_care',
    'tribunal federal de justicia administrativa',
    'universidad autonoma chapingo',
    'universidad autonoma metropolitana',
    'instituto nacional de neurologia y neurocirugia manuel velasco suarez',
    'administracion portuaria integral de salina cruz',
    'instituto nacional del suelo sustentable',
    'secretaria de las mujeres_care',
    'secretaria de las mujeres',
    'instituto nacional de electricidad y energias limpias',
    'ternium mexico',
    'ipn canal once - infinitum',
    'inapam',
    'talleres graficos de mexico',
    'colegio nacional de educacion profesional  tecnica_care',
    'fideicomiso del espacio cultural y educativo betlemitas',
    'cinvestav_care',
    'aicm',
    'colegio de postgraduados',
    'colegio de bachilleres del estado de campeche',
    'poder ejecutivo del estado de campeche',
    'j garcia lopez',
    'comision nacional del sistema de ahorro para el retiro_care',
    'dr mexico',
    'comision nacional de energia',
    'secretaria de cultura instituto nacional de las lenguas indigenas inali',
    'comision nacional antimonopolio',
    'api de mazatlan',
    'gobierno del edo de chihuahua',
    'ipab',
    'instituto nacional de astrofisica optica y electronica'
  )
),
inserted AS (
  INSERT INTO "ContratoMarco" ("id","siglasIm","company","serviceRef","note","createdBy","createdAt")
  SELECT id, "siglasIm", company, "serviceRef", note, "createdBy", "createdAt"
  FROM to_move
  ON CONFLICT (id) DO NOTHING
  RETURNING id
)
DELETE FROM "ClienteTop"
WHERE id IN (SELECT id FROM to_move);

-- 4. Insertar los que no estaban en ClienteTop (quedan con siglasIm/serviceRef vacíos)
INSERT INTO "ContratoMarco" ("id","siglasIm","company","serviceRef","createdBy","createdAt")
SELECT
  gen_random_uuid()::text,
  '',
  nombre,
  '',
  'migration',
  NOW()
FROM (VALUES
  ('ARCHIVO GENERAL DE LA NACION'),
  ('ASEA HIDROCARBUROS'),
  ('COMISION NACIONAL DE HIDROCARBUROS'),
  ('COMISION NACIONAL DE SEGUROS Y FIANZAS (CNSF)'),
  ('COMISION NACIONAL DE USUARIOS DE SERVICIOS FINANCIEROS (CONDUSEF)'),
  ('CONACYT_CARE'),
  ('CONAHCYT'),
  ('CONALITEG'),
  ('CONANP PEXA'),
  ('EXPORTADORA DE SAL'),
  ('FIDEICOMISO DE FOMENTO MINERO'),
  ('FINANCIERA NACIONAL DE DESARROLLO AGROPECUARIO RURAL FORESTAL Y PESQUERO'),
  ('FONACOT_CARE'),
  ('FONDO NACIONAL DE FOMENTO AL TURISMO FONATUR'),
  ('FONDO NACIONAL PARA EL FOMENTO DE LAS ARTESANIAS (FONART)'),
  ('GRUPO AEROPORTUARIO FERROVIARIO Y DE SERVICIOS AUXILIARES OLMECA MAYA MEXICA'),
  ('IMCINE'),
  ('INSTITUTO DE INVESTIGACIONES DR. JOSE MA. LUIS MORA_CARE'),
  ('INSTITUTO MEXICANO DE LA PROPIEDAD INDUSTRIAL (IMPI)'),
  ('INSTITUTO NACIONAL DE ECOLOGIA Y CAMBIO CLIMATICO'),
  ('INSTITUTO NACIONAL DE NEUROLOGIA Y NEUROCIRUGIA'),
  ('INSTITUTO NACIONAL DE SALUD PUBLICA'),
  ('INSTITUTO PARA LA PROTECCION AL AHORRO BANCARIO CARE'),
  ('PROCURADURIA DE LA DEFENSA DEL CONTRIBUYENTE (PRODECON)'),
  ('PROFEPA'),
  ('SECRETARIA DE ECONOMIA'),
  ('SECRETARIA DE EDUCACION PUBLICA SEP'),
  ('SECRETARIA DE RELACIONES EXTERIORES'),
  ('SECRETARIA EJECUTIVA DEL SISTEMA NACIONAL ANTICORRUPCION (SESNA)'),
  ('SEMARNAT'),
  ('SENASICA'),
  ('ADMINISTRACION PORTUARIA INTEGRAL DE VERACRUZ'),
  ('AEFCM'),
  ('AEROPUERTOS Y SERVICIOS AUXILIARES'),
  ('AGENCIA ESPACIAL MEXICANA'),
  ('AGROASEMEX'),
  ('B DRIVE - INSABI'),
  ('B DRIVE - PROFEPA'),
  ('B DRIVE - SFP'),
  ('B DRIVE CIMAT'),
  ('B DRIVE IMER'),
  ('B DRIVE INPRF'),
  ('B DRIVE IT - IMPI'),
  ('B DRIVE SPR'),
  ('CASA DE MONEDA DE MEXICO'),
  ('CENTRO DE ENSENANZA TECNICA INDUSTRIAL'),
  ('CENTRO DE INVESTIGACION EN MATEMATICAS'),
  ('CENTRO DE INVESTIGACION Y ASISTENCIA EN TECNOLOGIA Y DISENO DEL ESTADO DE JALISCO'),
  ('CENTRO DE INVESTIGACION Y DOCENCIA ECONOMICAS'),
  ('CENTRO FEDERAL DE CONCILIACION Y REGISTRO LABORAL'),
  ('CENTRO GEO'),
  ('CIATEQ'),
  ('CIBNOR'),
  ('CINETECA NACIONAL'),
  ('CINVESTAV'),
  ('CNSF OFICINA CORPORATIVA'),
  ('COLEGIO NACIONAL DE EDUCACION PROFESIONAL TECNICA'),
  ('COMISION NACIONAL BANCARIA Y DE VALORES'),
  ('COMISION NACIONAL DE CULTURA FISICA Y DEPORTE'),
  ('COMISION NACIONAL DE SEGURIDAD NUCLEAR Y SALVAGUARDIAS'),
  ('COMISION NACIONAL DE VIVIENDA'),
  ('CONAPESCA'),
  ('CONDUSEF OFICINAS REMOTAS'),
  ('CONSEJO NACIONAL DE FOMENTO EDUCATIVO'),
  ('CONUEE'),
  ('FIDEICOMISO DE RIESGO COMPARTIDO'),
  ('FIFONAFE'),
  ('FONATUR INFRAESTRUCTURA'),
  ('FONDO NACIONAL PARA EL FOMENTO DE LAS ARTESANIAS'),
  ('GRUPO AEROPORTUARIO DE LA CIUDAD DE MEXICO'),
  ('HOSPITAL GENERAL DE MEXICO'),
  ('HOSPITAL INFANTIL DE MEXICO FEDERICO GOMEZ'),
  ('HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DEL BAJIO'),
  ('IMP'),
  ('IMSS RED DE FUNCIONARIOS'),
  ('INDAABIN'),
  ('INEEL'),
  ('INIFED'),
  ('INSTITUTO DE ECOLOGIA (INECOL)'),
  ('INSTITUTO MEXICANO DE LA RADIO'),
  ('INSTITUTO NACIONAL DE ANTROPOLOGIA E HISTORIA'),
  ('INSTITUTO NACIONAL DE CARDIOLOGIA IGNACIO CHAVEZ'),
  ('INSTITUTO NACIONAL DE GERIATRIA'),
  ('INSTITUTO NACIONAL DE PERINATOLOGIA'),
  ('INSTITUTO NACIONAL DE PSIQUIATRIA RAMON DE LA FUENTE MUNIZ'),
  ('INSTITUTO NACIONAL DE ENFERMEDADES RESPIRATORIAS ISMAEL COSIO VILLEGAS'),
  ('INSTITUTO NACIONAL PARA LA EDUCACION DE LOS ADULTOS'),
  ('INSTITUTO POTOSINO DE INVESTIGACION CIENTIFICA Y TECNOLOGICA'),
  ('IPN CANAL ONCE'),
  ('ITSON'),
  ('LOTERIA NACIONAL'),
  ('ORGANISMO PROMOTOR DE MEDIOS AUDIOVISUALES'),
  ('PRESIDENCIA DE LA REPUBLICA'),
  ('PROCURADURIA AGRARIA'),
  ('PROCURADURIA DE LA DEFENSA DEL CONTRIBUYENTE'),
  ('PROCURADURIA FEDERAL DEL CONSUMIDOR'),
  ('PRONABIVE'),
  ('REGISTRO AGRARIO NACIONAL'),
  ('SADER'),
  ('SECRETARIA DE MEDIO AMBIENTE Y RECURSOS NATURALES'),
  ('SEDATU'),
  ('SENER'),
  ('SEP'),
  ('SEP OFICINAS CORPORATIVAS'),
  ('SERVICIO GEOLOGICO MEXICANO'),
  ('SIAP'),
  ('SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL DE LA FAMILIA'),
  ('SNICS'),
  ('TELEVISION METROPOLITANA'),
  ('TRIBUNAL SUPERIOR AGRARIO'),
  ('UNIVERSIDAD PEDAGOGICA NACIONAL'),
  ('ADMINISTRADORA DE CAJA BIENESTAR'),
  ('ALTO COMISIONADO DE LAS NACIONES UNIDAS PARA LOS REFUGIADOS'),
  ('AUDITORIA SUPERIOR DE LA FEDERACION'),
  ('CENTRO DE INGENIERIA Y DESARROLLO INDUSTRIAL'),
  ('COLEGIO DE BACHILLERES'),
  ('COMESA'),
  ('COMISION NACIONAL DE SEGUROS Y FIANZAS'),
  ('CONSEJERIA JURIDICA DEL EJECUTIVO FEDERAL'),
  ('EL COLEGIO DE LA FRONTERA SUR'),
  ('FONHAPO'),
  ('HOSPITAL JUAREZ DE MEXICO'),
  ('INAI'),
  ('INAPESCA'),
  ('INSTITUTO MEXICANO DE LA JUVENTUD'),
  ('INSTITUTO MEXICANO DE TECNOLOGIA DEL AGUA'),
  ('INSTITUTO MEXICANO DEL PETROLEO'),
  ('INSTITUTO NACIONAL DE CIENCIAS PENALES'),
  ('ITESI IRAPUATO'),
  ('P.M.I. COMERCIO INTERNACIONAL'),
  ('PMI COMERCIO INTERNACIONAL EXPRESS ROUTE'),
  ('RADIO SQCS'),
  ('SCANIA COMERCIAL'),
  ('SECRETARIA DE ECONOMIA DATA CENTER'),
  ('SECRETARIA DE LA FUNCION PUBLICA'),
  ('SECTUR'),
  ('SEPOMEX'),
  ('SKY'),
  ('UNISON'),
  ('SEDATU_CARE'),
  ('TRIBUNAL FEDERAL DE JUSTICIA ADMINISTRATIVA'),
  ('UNIVERSIDAD AUTONOMA CHAPINGO'),
  ('UNIVERSIDAD AUTONOMA METROPOLITANA'),
  ('INSTITUTO NACIONAL DE NEUROLOGIA Y NEUROCIRUGIA MANUEL VELASCO SUAREZ'),
  ('ADMINISTRACION PORTUARIA INTEGRAL DE SALINA CRUZ'),
  ('INSTITUTO NACIONAL DEL SUELO SUSTENTABLE'),
  ('SECRETARIA DE LAS MUJERES_CARE'),
  ('SECRETARIA DE LAS MUJERES'),
  ('INSTITUTO NACIONAL DE ELECTRICIDAD Y ENERGIAS LIMPIAS'),
  ('TERNIUM MEXICO'),
  ('IPN CANAL ONCE - INFINITUM'),
  ('INAPAM'),
  ('TALLERES GRAFICOS DE MEXICO'),
  ('COLEGIO NACIONAL DE EDUCACION PROFESIONAL  TECNICA_CARE'),
  ('FIDEICOMISO DEL ESPACIO CULTURAL Y EDUCATIVO BETLEMITAS'),
  ('CINVESTAV_CARE'),
  ('AICM'),
  ('COLEGIO DE POSTGRADUADOS'),
  ('COLEGIO DE BACHILLERES DEL ESTADO DE CAMPECHE'),
  ('PODER EJECUTIVO DEL ESTADO DE CAMPECHE'),
  ('J GARCIA LOPEZ'),
  ('COMISION NACIONAL DEL SISTEMA DE AHORRO PARA EL RETIRO_CARE'),
  ('DR MEXICO'),
  ('COMISION NACIONAL DE ENERGIA'),
  ('SECRETARIA DE CULTURA INSTITUTO NACIONAL DE LAS LENGUAS INDIGENAS INALI'),
  ('COMISION NACIONAL ANTIMONOPOLIO'),
  ('API DE MAZATLAN'),
  ('GOBIERNO DEL EDO DE CHIHUAHUA'),
  ('IPAB'),
  ('INSTITUTO NACIONAL DE ASTROFISICA OPTICA Y ELECTRONICA')
) AS t(nombre)
WHERE lower(trim(nombre)) NOT IN (SELECT lower(trim(company)) FROM "ContratoMarco");

-- Verificar resultado
SELECT 'ContratoMarco' AS tabla, COUNT(*) AS total FROM "ContratoMarco"
UNION ALL
SELECT 'ClienteTop', COUNT(*) FROM "ClienteTop";
